//put your sequence here, json formatted, unique key.
var sequenses={
    "tusc7": "GGGGTACCAAAGTCCACTCTGAGCTTTTCCTCTGGGAACAGATCCCAGATTATTCCAGACTTAAGACATGGAGATATATCTTGCTAGAGGTAGGAAGATGATAAGATCAGTTTCTATAGGTAGAGGATAATGTGTCCTAAAATGTAGGTAGAGATAAGTCTGACAGTGGTTTAGACAAAAAGGGCCTCTGCTAATGGTGGAGAGATCAAGGAAGAAAAGAGCAACGTTAAAGTGAGGCTGTACCCACAGATCATGCTCAAGCAAATTCGAACCGTGAGCGCATTTCTCTTAAACAATGAACACTTAGAATAAAAATTAAAATTTCCCACAAATTTCTAATTTTAAAATAGTTTCCCAAGATTTCAGTGGTATTGTATATATGCCCATATAATTTTTTGGATTACTATTCCCACAAGTGTAAGATGAAAGAGGACCTGCCCTCCATTCTATCTACTCCCTCTCTGCAAAGGCCATTTTGAAGATCTCAGTTTTACTGAAAGGGGTCTGCCACACATAACTTCCCTGGTGTACCAGCAACAAGTGTTCAGTGGACCATGGCAACACAAAGAATGACGGAGGAGAGAAAATGCCATGCAGAAGTGATAGTCAAGATGAAGATGTGGGAGAGGAGCAGCCCCCAGTATATATTCAGTGTGTCCTCTGAAGTAACAACCATCCCATCTGGCTGAGAAGTGATGGACACGGCTCCTTAACCACACTGTACCCTCTGTTCTTGGCACCTCTCTACCAGAAAGATATCAACAAATTGGATGGAATTCAGAGAACAGTAAGAAAAATGATTAAAGAGATGGAGGCAGTGACTTATGAGGAAAGATGAAAAGGACTAAATCTATGTAGCTTGGCAAAGCAACAACTGAGGTGGCGTATGAAAACTGTCTACAAGCATTTGAAGAATATAAACACCAAGGGAAGAGAGGGAACTTTTTAGAATGGTCTGGGGAATAAGCAGAGTAAGAGGACAGAATTGAAGAAAGGAGAGAGATATGCTAAGTTGGGGGTGGGGGCGTTTTCTCATCAATTGTAAATTTTGATAAATAACAAAATTAAGTCTGGAGAGAAAGAGTTGCATCTCATGCTTTTAGGTTACAATCAGTGTTGACCTGCACTGAGAAAATGTGACTTCCTATTATCCTTCTCAAAGTTATTGCTGCAGAGGAAAGAAGCATACATCTTTTACCCACCAGGAAACCCCCAAAGCATCTATTACCATAATAGCCATGGGAAACAGAAGGCACCTCAAATAAAGGTGGGGAAAAGAATGAAAGAAATGGCTTTGGCCTGTGCCTGTTTGACCTCTGAGAGATACTTTTTGCAAGAAATTGTTAAGTTTTGGCCCAAAAAGTGGTCGGTCTTTTATCCTTCCTTGTGGAGGCCAAACTGCAAACCAGGATGAAGAAACCATCAGTGGCAGTTTGGGGAGGTGGAGGAGGGACTATCTAGACTCAGTGAATCACCAAGGAAACATGAGGCCTATTTCTCTGTGAAGCTGAACTTCAAAAAACAATCTAAGAGATACAAAGGGAAAAGTGTGACTGCTCTGACAGCAAAAACAAGCAAATATCTCCAGAGGGGATTAATCCTTCTGCTTCAAAGTAACTAAAACAAAGAAAGCTGAGCCAGCTTCACTGGAAACAACACCTGTCCATCAGACAAGGATGAGCTAATCAAAAGAAAACACTGCCTATGTGCACGACTCAGCAGCCTGGACAGCTAATACCAAGGAACACGTTTTCACTATAAAGATTCAGCTTTCAAAATCCAGTTCCCTCTTGTAGAGCCACAGGGTTAAAAGGGACCTTAGAGATCATCTACATACAGGCCAAACCCTCAATGAATGCCAGTGTTCGCCTTATGTTCTTCTTGCCGGACTCTTTTCTGGCCTCTGTTCTGTCAGGATGTTTCCTGTTTTGCAAAACAGCTTTAATCCTTGAGTATATTTAATTGTTAGAAAACAGTTCCTCAAATTTGACCCCAAATTTAAGTCTAATTTATGAAGAAAGTTTTGCCTTTGGAGACAGGTTTAATTTTACTTCCATGTGGAAAACCTTCAAATAAAATGATGACTATTGTGTACTCACGAAAAA",
    "linc00951": "CTTTGAACCATGGGAGAAGATGTTCTGGGGTCAACTTCAAGACAGGGCTGGCAGTACTGGGACACTTGGCTGAGAAACAGGGGGCCTGCCCAGGTAAAGAGCTTCCCCCCATGGACGTAAATGGAGGGTCACAGCTGAGCTTCAGGAAGGGAAGGAAAGGAAAAGAAGGAGCAAGGAGTATGGGGGCACACTTTCTCCTCATACTGGGATTCCAGCTCACATCCCAGTCCTTCCCAGTGAGCAGTCATGAGAACCTCACCCTGAGAAAGGAGGCAGCGATGGGGCTTTTCTCTAGGTGCCCTAGCTCTCCCTCTCCACTGAAGTTGGAGACTAGACACTGGTGGTGGAGGGGCAGAAACTTAGGCCCCAGGTCCTATGAGCAGATCCCTCTACAGGTACCTGGGGCTCAGATGGTATAAGACAGGAAGGAGGGAGCCTGGGTAGGGTCAGGTGGTGGCTCCCCACAATTAGAAAACATGGCTTTTCTGCATGCATTTCTTTGGATGGGTGAGGTGGTCTCCTGCCCTGTATTCTTGCTTGACCAATAATCACAGGCTTTGATTCTTGTGAAAGAACAAGAAAGTCAGGAGACATCTGGAACAAAGGCAGCAGCAGGAAGAGCAACACAGATGCAATATAGTGTCAGGTATAGCCCGGCTTACTGTCCCCAACTAGGCAGCAAGATCAATCAGCCTCCCTCACAGAAACCAGCAGAATGGGGCATTGTGATTTTGATGATTTTTTTATTGTATTGAGAACACTTCACTTGAGATCTCCTCCCTTAACAAGTTTTTAAGTGTACAATAAGCTATTGTTAACTACAACAATGTACAACAACATTGTACAGCAGATTTCTAGAATGTATTCACCTTGCATGACTGAAACTGTGTACCTATTGAATAACAACTCTCCATCTCCCCCTCCTCCCAGTCCCTGGCAACCACCATTCCACTCTCTGCTTCTGGGAGTTTGACTATTTTAGATACTCCATATAAGTGAAATCCAGCAATCCTACTCCTGGGTATTCATCCAAAAGAATTAAAATCAGGTTCTCAGACATGCACTTCCATGTTGATTGCATTATCCACAACAGCCAAGATGTGGAGGCAACCTTGGTGTTCATTAACGAAGGAGCGGTTAAAGAAAAGTGGAATATACATGTAACGGAGTAGAATTCAGCCTTAGCAAAGAAGGAAATCCTGCCATATGCAACAACATGGGAAGTGGTGAGGGCTTTCACTAGAGGTAGGGGTGGAGAAGGAAGCTTCTTAGGGTAGTTTAAGGAGGTAGGAAGCAACATCACAGTTTGGCCACATCTCCTTCCTGTAGGAAATACAAAATCCAAAGAGACACAAAGAGAAGAGAGAAAGAAAATATAGCAAACATTCTAATGCCATCTTTGCTACTGGACTTGTACACGTTTTACTGCCATTTCTCATTTCACCCTCAGAATAACCTCTGAAGAGGTCATTGTAGTTCCCATTTTACAGACAAGGTCTCTGGGCTGGTAGAAGGCCTGGGTAGGATGGTTATTCATGAGCTGAGAAGGAGAATCTCAGACCACCACAGTGGGTGCTCTCAGGACCATTCCAAGGCTTTCTGGCTAAGAGTCCAGGGGAACATCACCTGGGGCTAGGGAAGAGCTTTTGGAACCAAGAGCTCCAAAGGCTGGGATTGCCCAAGAGGACAAGGGGGAGGGGCATGTTGGGCACCTTGCAGTGTGGTGATTCCAGAGGCATGCACCCTGGCTTGCCAAATGTCTCAGAGGGCTTGGGCTCCACAGGCCCTCTGCTATGGAGAGCTTTTCTCAGCCCTTTCCACCTACTACATGATTCTAGGAATCTTCTTCTGTGGAAGGAGGAGCTTTGGGAATCTGCTGGGCTGCAGAGGTAGTCCCCATCCAGCTCTATGCCACTAGTGACAGCTCCAGAGTTTTGCTCTCACCAACACCCACATGCTTCTGCTCTATAAAGATATCATATTTACATATTGACCTTCTTGCCCCTCCTACTGTATGAACCACACTCACAAATGCACACACGAAGGCTTTGAGCAGCATTGAAATTGATCAAGCCTGAGTATCATAGAACAAGTGTCCTATCTGCTAGAGTTTGGCTGTACCTTGACCTCAGATATCTGCCATTCAGAATGGAATGCCCAGCTCTGGGCAGGCACTGGATCAGAACAACCATAAGCTTAGGCATCTGCTTCTCCCTCTTTCTCCACCTCCATGTCAAGGGCACCCCCTCACTACAAACTGGGCCTGGGGTGGTGGTATAAGGCATGGGGCAGGGAACTGGGAAGCTCCCTCCACCCCATCTGATTTCAGACCTGCCTCCTCAGTGCCCCATGTGTGACCCAGCTATATTTAGCAAGCTCAATTCAGTAACTAGAGCAACTGGTCTAGCGCCCTCCCCTTCCAAGGACTCTGAAGGGGCCAGTTTCTCACACCTTTTAATCATCTTCCATTTCTCCAGGCAACCAACACAAAAGGCCTGGACCAGGTGGTGGAGATGCTGGGGCTCCTACACAGAGGCTCTATTTTCTGTTTGCAGTCTTCCAGGCCAGATAAGAAAACTGAGACACAGAAAAGTCACACAAGATTATCGAGGTCAACACAGAGAACAGTGGAACCTGCACCTGACCCCAGGCAGGCGGAACCTTCATGACCACACCACACCACCACAGGGAACAGGCAGGGAAAACAATGGGTCTAGCAGGACAAAAGTGACATTTCCCAGAGTTTCTTGCTGTTTGGATCTGGCTGCAGTTTCAGTTTTGCCAAGAAGAGGCATTTCCATGAGCTCTGGACAGTGGCAGAGAGGCAGAGGTGCTCCACTGCAGTGTGCTGGATGGTCCACGGGCTCCTGCCAATGTGAGGATTTGCAGCAACTGGTATATCCATGGTCTTGTCACCAGCTTCCTGAATTCGGGGCAGCTGGAGCCACACTAGTGGTCCTTCCTTGCAGGGGCAGCAGCTGTCTCCTGGTCTCAGAATCACAGCTGTGGGGATGCAACCTTAAGCCAAAAGCCTAGCGGTGGGTGGTCCTAAACTTCTTTTGTCTAGGCCCTCTGATCCCTCTGTAAGTCGCTATTTCCCTTATTAAATCTCTTTCTGCTGG",
};


$('body').html('id      \tkey        \t$id    \tgc     \tposition\t sequence\n<br/>');
var g = {};//global variable
var i=0;//
var intervalTime=1000;//interval time
var failKeys = "";//failed keys
var failToSuccess = "";//first-fail-then-success keys
var finish = 0; //count
function getResults(d,key) {
    var data = {"assayName":"AAA","geneName":"","organism":"Human","otherOrganism":"","probeSequence":"> tusc7 \nGGGGTACCAAAGTCCACTCTGAGCTTTTCCTCTGGGAACAGATCCCAGATTATTCCAGACTTAAGACATGGAGATATATCTTGCTAGAGGTAGGAAGATGATAAGATCAGTTTCTATAGGTAGAGGATAATGTGTCCTAAAATGTAGGTAGAGATAAGTCTGACAGTGGTTTAGACAAAAAGGGCCTCTGCTAATGGTGGAGAGATCAAGGAAGAAAAGAGCAACGTTAAAGTGAGGCTGTACCCACAGATCATGCTCAAGCAAATTCGAACCGTGAGCGCATTTCTCTTAAACAATGAACACTTAGAATAAAAATTAAAATTTCCCACAAATTTCTAATTTTAAAATAGTTTCCCAAGATTTCAGTGGTATTGTATATATGCCCATATAATTTTTTGGATTACTATTCCCACAAGTGTAAGATGAAAGAGGACCTGCCCTCCATTCTATCTACTCCCTCTCTGCAAAGGCCATTTTGAAGATCTCAGTTTTACTGAAAGGGGTCTGCCACACATAACTTCCCTGGTGTACCAGCAACAAGTGTTCAGTGGACCATGGCAACACAAAGAATGACGGAGGAGAGAAAATGCCATGCAGAAGTGATAGTCAAGATGAAGATGTGGGAGAGGAGCAGCCCCCAGTATATATTCAGTGTGTCCTCTGAAGTAACAACCATCCCATCTGGCTGAGAAGTGATGGACACGGCTCCTTAACCACACTGTACCCTCTGTTCTTGGCACCTCTCTACCAGAAAGATATCAACAAATTGGATGGAATTCAGAGAACAGTAAGAAAAATGATTAAAGAGATGGAGGCAGTGACTTATGAGGAAAGATGAAAAGGACTAAATCTATGTAGCTTGGCAAAGCAACAACTGAGGTGGCGTATGAAAACTGTCTACAAGCATTTGAAGAATATAAACACCAAGGGAAGAGAGGGAACTTTTTAGAATGGTCTGGGGAATAAGCAGAGTAAGAGGACAGAATTGAAGAAAGGAGAGAGATATGCTAAGTTGGGGGTGGGGGCGTTTTCTCATCAATTGTAAATTTTGATAAATAACAAAATTAAGTCTGGAGAGAAAGAGTTGCATCTCATGCTTTTAGGTTACAATCAGTGTTGACCTGCACTGAGAAAATGTGACTTCCTATTATCCTTCTCAAAGTTATTGCTGCAGAGGAAAGAAGCATACATCTTTTACCCACCAGGAAACCCCCAAAGCATCTATTACCATAATAGCCATGGGAAACAGAAGGCACCTCAAATAAAGGTGGGGAAAAGAATGAAAGAAATGGCTTTGGCCTGTGCCTGTTTGACCTCTGAGAGATACTTTTTGCAAGAAATTGTTAAGTTTTGGCCCAAAAAGTGGTCGGTCTTTTATCCTTCCTTGTGGAGGCCAAACTGCAAACCAGGATGAAGAAACCATCAGTGGCAGTTTGGGGAGGTGGAGGAGGGACTATCTAGACTCAGTGAATCACCAAGGAAACATGAGGCCTATTTCTCTGTGAAGCTGAACTTCAAAAAACAATCTAAGAGATACAAAGGGAAAAGTGTGACTGCTCTGACAGCAAAAACAAGCAAATATCTCCAGAGGGGATTAATCCTTCTGCTTCAAAGTAACTAAAACAAAGAAAGCTGAGCCAGCTTCACTGGAAACAACACCTGTCCATCAGACAAGGATGAGCTAATCAAAAGAAAACACTGCCTATGTGCACGACTCAGCAGCCTGGACAGCTAATACCAAGGAACACGTTTTCACTATAAAGATTCAGCTTTCAAAATCCAGTTCCCTCTTGTAGAGCCACAGGGTTAAAAGGGACCTTAGAGATCATCTACATACAGGCCAAACCCTCAATGAATGCCAGTGTTCGCCTTATGTTCTTCTTGCCGGACTCTTTTCTGGCCTCTGTTCTGTCAGGATGTTTCCTGTTTTGCAAAACAGCTTTAATCCTTGAGTATATTTAATTGTTAGAAAACAGTTCCTCAAATTTGACCCCAAATTTAAGTCTAATTTATGAAGAAAGTTTTGCCTTTGGAGACAGGTTTAATTTTACTTCCATGTGGAAAACCTTCAAATAAAATGATGACTATTGTGTACTCACGAAAAA","maskingLevel":5,"numberMaxProbe":50,"oligoLength":20,"minSpacingLength":80};
    data.probeSequence = d;
    if(d) {
        $.ajax({
            url: '/api/v1/product/stellaris',
            type: 'post',
            contentType:"application/json",
            dataType: 'json',
            data: JSON.stringify(data),
        })
        .done(function(d) {
            if(g[key] > 1) {
                failToSuccess += key+",";
                console.log("first-fail-then-success keys:"+failToSuccess);
            }
            finish++;
            var content="";
            var probes = d.value.probes;
            for(var ind in probes){
                content+=key+"\t"+ind+"\t"+probes[ind].$id+"\t"+probes[ind].gc+"\t"+probes[ind].position+"\t"+probes[ind].sequence+"\n<br/>";
            }
            //$('body').append(key+':'+JSON.stringify(d.value.probes)+'<br/>*******<br/>');
            $('body').append(content);
        })
        .fail(function() {
            g[key]++;
            if(g[key] < 5) {
                getResults(d,key);
            }else{
                failKeys += key+",";
                finish++;
                console.log("5-times failed keys:"+failKeys);
            }
        })
        .always(function() {
            if(finish === i) {
                console.log('God',"first-fail-then-success keys:"+failToSuccess,"finally failed keys:"+failKeys);
            }
        });
    }else{
        finish++;
        console.log(key+" ,key is empty");
    } 
}

for(var key in sequenses) {
    var cur = sequenses[key];
    i++;
    g[key] = 0;
    (function(cur,key,i){
        
        setTimeout(function() {
            getResults(cur,key);
        },i*intervalTime);
    })(cur,key,i);
    console.log(i+":"+key);
}


